import Head from 'next/head'
import  React ,{ Suspense } from "react";
import { Inter } from '@next/font/google'
import { Navbar } from 'src/components'
import styles from 'styles/Home.module.css'
import Loader from 'src/components/Loader';

const inter = Inter({ subsets: ['latin'] })

const HomeScreen = React.lazy(() => import("src/pages/home"));
// const SendEther = React.lazy(() => import("./pages/SendEther"));
// const Lottery = React.lazy(() => import("./pages/Lottery"));
// const LotteryPool = React.lazy(() => import("./pages/LotteryPool"));
// const BuyToken = React.lazy(() => import("./pages/BuyToken"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Suspense fallback={<Loader full={true} />}>
            <HomeScreen />
        </Suspense>
      </main>
    </>
  )
}
